"""empty message

Revision ID: 46c1a4d9e368
Revises: bdbdec31f710
Create Date: 2021-03-22 14:11:42.614049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c1a4d9e368'
down_revision = 'bdbdec31f710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('edit_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_edit_time'), 'post', ['edit_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_edit_time'), table_name='post')
    op.drop_column('post', 'edit_time')
    # ### end Alembic commands ###
