"""Added Link model

Revision ID: d8daba1abda3
Revises: ce3e300a370d
Create Date: 2021-03-23 09:06:23.561075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8daba1abda3'
down_revision = 'ce3e300a370d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_link_timestamp'), 'link', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_timestamp'), table_name='link')
    op.drop_column('link', 'timestamp')
    # ### end Alembic commands ###
