"""Added Todo model

Revision ID: e7336410a36a
Revises: d8daba1abda3
Create Date: 2021-03-23 14:47:53.760093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7336410a36a'
down_revision = 'd8daba1abda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_created'), 'todo', ['created'], unique=False)
    op.create_index(op.f('ix_todo_modified'), 'todo', ['modified'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_modified'), table_name='todo')
    op.drop_index(op.f('ix_todo_created'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###
